version: "2"
services:
  master:
    image: modenaf360/hadoop-3.2:latest
    container_name: master
    hostname: master
    volumes:
      - ./masterdata:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - WORKER_NODE=slave1,slave2
      - NODE_TYPE=namenode
      - GOTTY_ID=modenaf360
      - GOTTY_PW=1234
    env_file:
      - ../../hadoop.env
    ports:
      - 8989:7777/tcp
      - 50070:50070/tcp
      - 8042:8042/tcp
      - 8085:8080/tcp
      - 8985:8085/tcp
      - 8088:8088/tcp
      - 9000:9000/tcp
      - 8031:8031/tcp
      - 19888:19888/tcp
    depends_on:
      - slave1
      - slave2
    links:
      - slave1:slave1
      - slave2:slave2
    network_mode: hadoop_cluster_default

  slave1:
    image: modenaf360/hadoop-3.2:latest
    container_name: slave1
    hostname: slave1
    volumes:
      - ./datanode1:/hadoop/dfs/name
    env_file:
      - ../../hadoop.env
    stdin_open: true
    tty: true
    privileged: true
    network_mode: hadoop_cluster_default


  slave2:
    image: modenaf360/hadoop-3.2:latest
    container_name: slave2
    hostname: slave2
    volumes:
      - ./datanode2:/hadoop/dfs/data
    env_file:
      - ../../hadoop.env
    stdin_open: true
    tty: true
    privileged: true
    network_mode: hadoop_cluster_default
